
[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

# [[keyboard.bindings]]
# chars = "\u0002u"
# key = "O"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u0002n"
# key = "Tab"
# mods = "Control"
#
# [[keyboard.bindings]]
# chars = "\u0002x"
# key = "W"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "ToggleFullScreen"
# key = "F11"

[window]
decorations = "Transparent" # Options are: Full, Transparent, Buttonless or None
dynamic_padding = false # True or False, default is false
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 8
y = 26

[general]

live_config_reload = true
import = [
  "/Users/rene/.config/alacritty/themes/catppuccin-mocha.toml"
  #"/Users//rene/.config/alacritty/themes/gruvbox_dark.toml"
]

