vim.cmd("ab :white_check_mark: ✅")
vim.cmd("ab :warning: ⚠")
vim.cmd("ab :bulb: 💡")
vim.cmd("ab :pushpin: 📌")
vim.cmd("ab :bomb: 💣")
vim.cmd("ab :pill: 💊")
vim.cmd("ab :construction: 🚧")
vim.cmd("ab :pencil: 📝")
vim.cmd("ab :point_right: 👉")
vim.cmd("ab :book: 📖")
vim.cmd("ab :link: 🔗")
vim.cmd("ab :wrench: 🔧")
vim.cmd("ab :info: 🛈")
vim.cmd("ab :telephone: 📞")
vim.cmd("ab :email: 📧")
vim.cmd("ab :computer: 💻")
